---
title: "Tytuł apki"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

dat<-read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

dat$Party<-recode(dat$dem,`1`="Democrat",`0`="Republican")


#######WSKAZÓWKA: dla Wykresu D będziesz musiał/a ustawić wysokość funkcji renderPlot, używając argumentu height. Spróbuj wartości 750.

#####niektóre funkcje zarządzania danymi są już dołączone. Musisz dodać funkcje wizualizacji.

```


Page 1
======

### Chart A


```{r}
dat %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed=sum(all_pass)) %>% 
  ggplot(aes(x=year, y=passed, fill=Party)) +
  geom_area() +
  scale_fill_manual(values = c(
      "Democrat" = "blue",
      "Republican" = "red"
    )) +
  labs(
    title = "Number of Bills Passed Since 1980",
    x = "Year",
    y = "All Bills Passed",
    fill = "Party"
  ) +
  theme_grey()

```

Page 2
======

Column 1
----------

### Chart B

```{r}

dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot(aes(x=votepct, y=all_pass, color=Party)) +
  geom_point() +
  geom_smooth(method = "loess", se=TRUE) +
  scale_color_manual(
    values = c(
      "Republican" = "red",
      "Democrat" = "blue"
    )
  ) +
  labs(
    title='Passage and Vote Pct., 110th Congress',
    x = "Vote percentage",
    y = "All bills passed",
    color = "Party"
  ) 
ggplotly()
```

Column 2
-----
### Chart C

```{r}
dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot(aes(x=dwnom1, y=all_pass, color=Party)) +
  
  geom_point() +
  geom_smooth(method = "lm", se=TRUE) +
  scale_color_manual(
    values = c(
      "Republican" = "red",
      "Democrat" = "blue"
    )
  ) +
  labs(
    title = 'Passage and Ideology Pct., 110th Congress',
    x = "Vote percentage",
    y = "All bills passed",
    color = "Party"
  )
ggplotly()
```

Page 3
======

Sidebar {.sidebar}
------

### State

```{r}
selectizeInput(
  inputId = "states",
  label = "State",
  choices = sort(unique(dat$st_name)),
  selected = sort(unique(dat$st_name)),
  multiple = TRUE,
  options = list(
    placeholder = "Choose states"
  )
)
```

Column
------

### Chart D

```{r}
renderPlot({

  req(input$states)

  dat %>%
    filter(
      congress == 110,
      st_name %in% input$states,
      !is.na(st_name),
      !is.na(all_pass)
    ) %>%
    group_by(st_name) %>%
    summarise(
      total_bills = sum(all_pass, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    arrange(st_name) %>%
    ggplot(aes(
      x = st_name,
      y = total_bills
    )) +
    geom_col(fill = "grey40") +
    coord_flip() +
    labs(
      title = "Total Bills Passed by State Delegations, 110th Congress",
      x = "State Name",
      y = "Total Bills Passed Per State"
    ) +
    theme_grey()

}, height = 750)
```